name: Getting Application Language

on:
  push:
    branches:
      - 'main'
env:
  Docker_File_PATH: src/Web/Dockerfile
  
jobs:
  identify_app_language:
    name: Language Identification
    runs-on: ubuntu-latest
    environment: testing

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checking Dockerfile
      run: |
        echo $Docker_File_PATH
        app=`grep -i FROM $Docker_File_PATH | egrep -i 'java|jre|dotnet|aspnet'`
        echo $app
        
